/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://zm6eg5f62fex3cyp4bz2r6afli.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b3h3z3fg5rhovgsz433eyel33a",
    "aws_cognito_identity_pool_id": "us-east-1:b991f5c4-82b7-4a1c-9a72-789f6a233a8a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_INbMftiAd",
    "aws_user_pools_web_client_id": "6np798e4vrm85dbgpdqm0i63vf",
    "oauth": {}
};


export default awsmobile;
